language: rust
rust:
  - stable
  - beta
  - nightly
before_script:
  - rustup component add clippy
  - rustup component add rustfmt
jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true
os:
  - linux
  - osx
  - windows
script:
  - RUSTFLAGS="-D warnings" cargo build --verbose
  - cargo test --verbose
  - cargo clippy -- -D warnings
  - cargo fmt --all -- --check
