language: rust
rust:
  - stable
  - beta
  - nightly
jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true
os:
  - linux
  - osx
  - windows
script:
  - RUSTFLAGS="-D warnings" cargo build --verbose
  - cargo test --verbose
